config/routes.rb
Rails.application.routes.draw do
  resources :requesters do 
    resources :credit_requests
  end

root "requesters#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit_request.rb
class CreditRequest < ApplicationRecord
  belongs_to :requester
  before_save :interest_rate

  validates_presence_of :value

  private 
  def interest_rate
    #rate = 0.15
    #months = 12
    #pmt = 1
    #PMT = valor_presente X ((((1 + taxa) ^ numero_de_periodos) X taxa) / (((1 + taxa) ^ numero_de_periodos) - 1))
    #100000 * ((((1.015) ** 12) * 0.015) / (((1.015) ** 12) - 1)) = 9167.999290622945
    self.total_value =  self.value * ((((1 + 0.15) ** 12) * 0.15) / (((1 + 0.15) ** 12) - 1)) 
    self.monthly_value = (self.total_value / 12)
  end
end

app/models/requester.rb
class Requester < ApplicationRecord
    has_many :credit_requests

    validates_presence_of :company_name, :cnpj, :address, :phone
    #validates :cnpj, :cnpj => true
    #validates_format_of :phone, with: /^\(11\) 9\d{4}-\d{4}|\((?:1[2-9]|[2-9]\d)\) [5-9]\d{3}-\d{4}$/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/credit_requests_controller.rb
class CreditRequestsController < ApplicationController
    before_action :set_requester

    def create
        @credit_request = @requester.credit_requests.create(credit_request_params)
        redirect_to @requester
    end

    def destroy
        @credit_request = @requester.credit_requests.find(params[:id])
        if @credit_request.destroy
            flash[:success] = "Credit Request was deleted."
        else
            flash[:error] = "Credit Request could not be deleted"
        end
        redirect_to @requester
    end

    private
    
    def set_requester
        @requester = Requester.find(params[:requester_id])
    end

    def credit_request_params
        params[:credit_request].permit(:value)
    end
end

app/controllers/requesters_controller.rb
class RequestersController < ApplicationController
  before_action :set_requester, only: [:show, :edit, :update, :destroy]

  # GET /requesters
  # GET /requesters.json
  def index
    @requesters = Requester.all
  end

  # GET /requesters/1
  # GET /requesters/1.json
  def show
  end

  # GET /requesters/new
  def new
    @requester = Requester.new
  end

  # GET /requesters/1/edit
  def edit
  end

  # POST /requesters
  # POST /requesters.json
  def create
    @requester = Requester.new(requester_params)

    respond_to do |format|
      if @requester.save
        format.html { redirect_to @requester, notice: 'Requester was successfully created.' }
        format.json { render :show, status: :created, location: @requester }
      else
        format.html { render :new }
        format.json { render json: @requester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requesters/1
  # PATCH/PUT /requesters/1.json
  def update
    respond_to do |format|
      if @requester.update(requester_params)
        format.html { redirect_to @requester, notice: 'Requester was successfully updated.' }
        format.json { render :show, status: :ok, location: @requester }
      else
        format.html { render :edit }
        format.json { render json: @requester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requesters/1
  # DELETE /requesters/1.json
  def destroy
    @requester.destroy
    respond_to do |format|
      format.html { redirect_to requesters_url, notice: 'Requester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requester
      @requester = Requester.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def requester_params
      params.require(:requester).permit(:company_name, :cnpj, :address, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_requests_helper.rb
module CreditRequestsHelper
end

app/helpers/requesters_helper.rb
module RequestersHelper
end

app/views/credit_requests/_credit_request.html.erb
<h2>Credit Request Information</h2>
<p><strong>Value Requested : </strong>    <%= number_to_currency(credit_request.value, :unit => "R$") %></p>
<p><strong>Total Value to Pay : </strong> <%= number_to_currency(credit_request.total_value, :unit => "R$") %></p>
<p><strong>Monthly Payment : </strong>    <%= number_to_currency(credit_request.monthly_value, :unit => "R$") %></p>
<p><strong>Duration in Months : </strong> 12 </p>
<%= link_to "Delete", requester_credit_request_path(@requester, credit_request.id), method: :delete, data: { confirm: "Are you sure?" } %>
<br/>

app/views/credit_requests/_form.html.erb
<%= form_for([@requester, @requester.credit_requests.build]) do |f| %>
 <%= f.text_field :value, placeholder: "New Credit Request" %>
 <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loan App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/requesters/_form.html.erb
<div class="left">
  <%= form_with(model: requester, local: true) do |form| %>
    <% if requester.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(requester.errors.count, "error") %> prohibited this requester from being saved:</h2>

        <ul>
          <% requester.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :company_name %>
      <%= form.text_field :company_name %>
    </div>
    
    <div class="field">
      <%= form.label :cnpj %>
      <%= form.text_field :cnpj %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>

    <div class="field">
      <%= form.label :phone %>
      <%= form.text_field :phone %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/requesters/edit.html.erb
<h2 class="card-header info-color white-text text-left">Editing Requester</h2>

<%= render 'form', requester: @requester %>


<h6 class="text-left"> <%= link_to 'Show', @requester %> |
<%= link_to 'Back', requesters_path %></h6>

app/views/requesters/index.html.erb
<div class="center">
<p id="notice"><%= notice %></p>

<h1>Requesters</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>CNPJ</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @requesters.each do |requester| %>
      <tr>
        <td><%= requester.company_name %></td>
        <td><%= requester.cnpj %></td>
        <td><%= requester.address %></td>
        <td><%= requester.phone %></td>
        <td><%= link_to 'Show', requester %></td>
        <td><%= link_to 'Edit', edit_requester_path(requester) %></td>
        <td><%= link_to 'Destroy', requester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Requester', new_requester_path %>
</div>

app/views/requesters/new.html.erb
<h2 class="card-header info-color white-text text-left">New Requester</h2>
<br/>
<%= render 'form', requester: @requester %>

<br/>
<h6 class="text-left"> |     <%= link_to 'Index', @requester %>     | 
<%= link_to 'Back', requesters_path %> | </h6>

app/views/requesters/show.html.erb
<form class ="text-center border-light p-5">
  <p id="notice"><%= notice %></p>
  <h2 class="card-header info-color white-text text-center">Requester Information</h2>
  <p>
    <strong>Company Name:</strong>
    <%= @requester.company_name %>
  </p>

  <p>
    <strong>CNPJ:</strong>
    <%= @requester.cnpj %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @requester.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @requester.phone %>
  </p>

  <br/>
    <div id="credit_requests_wrapper">
      <%= render @requester.credit_requests %>
      <div id="form">
      <br/>
      <%= render "credit_requests/form" %>
    </div>
  </div>

  <p class="text-center"> <%= link_to 'Edit', edit_requester_path(@requester) %> |
  <%= link_to 'Back', requesters_path %> </p>
</form>